2025-04-16 12:27:26,637 INFO django.server: "GET /api/v1/dashboard/ HTTP/1.1" 200 5219
2025-04-16 12:28:48,387 INFO django.server: "GET /api/v1/dashboard/ HTTP/1.1" 200 5219
2025-04-16 12:28:49,282 INFO django.server: "GET /api/v1/dashboard/ HTTP/1.1" 200 5219
2025-04-16 12:29:00,388 INFO django.server: "GET /api/v1/dashboard/ HTTP/1.1" 200 5219
2025-04-16 12:29:01,001 INFO django.server: "GET /api/v1/dashboard/ HTTP/1.1" 200 5219
2025-04-16 12:29:01,643 INFO django.server: "GET /api/v1/dashboard/ HTTP/1.1" 200 5219
2025-04-16 16:04:14,524 INFO django.server: "GET /api/v1/dashboard/ HTTP/1.1" 200 5219
2025-04-16 16:04:17,239 INFO django.server: "GET /api/v1/dashboard/ HTTP/1.1" 200 5219
2025-04-16 16:11:58,590 INFO django.server: "GET /api/v1/orders/ HTTP/1.1" 200 6827
2025-04-16 16:12:44,669 INFO django.server: "GET /api/v1/orders/ HTTP/1.1" 200 6827
2025-04-16 16:12:49,978 ERROR django.request: Internal Server Error: /api/v1/orders/
Traceback (most recent call last):
  File "C:\Users\Zoreyan\Desktop\LogAnalyzer\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Zoreyan\Desktop\LogAnalyzer\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Zoreyan\Desktop\LogAnalyzer\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Zoreyan\Desktop\LogAnalyzer\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zoreyan\Desktop\LogAnalyzer\venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zoreyan\Desktop\LogAnalyzer\venv\Lib\site-packages\rest_framework\views.py", line 429, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
2025-04-16 16:12:49,982 ERROR django.server: "POST /api/v1/orders/ HTTP/1.1" 500 80559
